export const MAIN = {
  START_QUESTION: 'START_QUESTION',
  INITIAL_OPTIONS: 'INITIAL_OPTIONS',
  SITE_OPTIONS: 'SITE_OPTIONS',
  LESSON_OPTIONS: 'LESSON_OPTIONS',
  PROD_OPTIONS: 'PROD_OPTIONS',
  COURSE_OPTIONS: 'COURSE_OPTIONS',
  USER_OPTIONS: 'USER_OPTIONS',
  FINAN_OPTIONS: 'FINAN_OPTIONS',
  SITE_CONFIG_OPTIONS: 'SITE_CONFIG_OPTIONS',
  STORE_OPTIONS: 'STORE_OPTIONS',
  RESET: 'RESET',

  SITE_MY_COURSES: 'SITE_MY_COURSES',
  SITE_FORUM: 'SITE_FORUM',
  SITE_PROFILE: 'SITE_PROFILE',
  SITE_BANNERS: 'SITE_BANNERS',
  SITE_SECTIONS: 'SITE_SECTIONS',
  SITE_SOCIAL: 'SITE_SOCIAL',
  SITE_CERTIFICATE: 'SITE_CERTIFICATE',
  
  FINAN_TAXES: 'FINAN_TAXES',
}